import type { Role } from "./roles"

export const PERMISSIONS = {
  // Genérico

  //========= REGISTROS==========
  CREATE_BRANCH: "CREATE_BRANCH",
  CREATE_PERSONAL: "CREATE_PERSONAL",
  CREATE_CAR: "CREATE_CAR",
  CREATE_CUSTOMER: "CREATE_CUSTOMER",

//========== SOLICITUDES ==========
  CREATE_REGDEPOSIT: "CREATE_REGDEPOSIT",
  CREATE_REGTRANSACTION: "CREATE_REGTRANSACTION",   

  // ======== INGRESOS ==========
  DEPOSITS: "DEPOSITS",
  MEMORANDUM: "MEMORANDUM",

  // ======== EGRESOS  =========
  PAGO_COMISION: "PAGO_COMISION",
  PAGO_SOLICITUDES: "PAGO_SOLICITUDES",
  PAGO_COMPRAS: "PAGO_COMPRAS",
  RESTITUCIONES: "RESTITUCIONES",

  //======== CIERRES =========
  CIERRE_CAJA: "CIERRE_CAJA"

} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  
  GERENTE: [
    PERMISSIONS.CREATE_BRANCH,
    PERMISSIONS.CREATE_PERSONAL,
    PERMISSIONS.CREATE_CAR,
    PERMISSIONS.CREATE_CUSTOMER,
    PERMISSIONS.CREATE_REGTRANSACTION,
    PERMISSIONS.CREATE_REGDEPOSIT,  
    PERMISSIONS.DEPOSITS,
    PERMISSIONS.MEMORANDUM,
    PERMISSIONS.PAGO_COMISION,  
    PERMISSIONS.PAGO_COMPRAS,
    PERMISSIONS.PAGO_SOLICITUDES,
    PERMISSIONS.RESTITUCIONES
  ],

  ADMIN: [
    PERMISSIONS.CREATE_BRANCH,
    PERMISSIONS.CREATE_PERSONAL,
    PERMISSIONS.CREATE_CAR,
    PERMISSIONS.CREATE_CUSTOMER,    
    PERMISSIONS.CREATE_REGTRANSACTION,
    PERMISSIONS.CREATE_REGDEPOSIT,  
    PERMISSIONS.DEPOSITS,
    PERMISSIONS.MEMORANDUM,
    PERMISSIONS.PAGO_COMISION,  
    PERMISSIONS.PAGO_COMPRAS,
    PERMISSIONS.PAGO_SOLICITUDES,
    PERMISSIONS.RESTITUCIONES,
    PERMISSIONS.CIERRE_CAJA
  ],

  JEFE_PERSONAL: [
    PERMISSIONS.CREATE_PERSONAL,
    PERMISSIONS.CREATE_REGTRANSACTION,
    PERMISSIONS.CREATE_REGDEPOSIT,
    PERMISSIONS.CREATE_CAR,
    PERMISSIONS.CREATE_CUSTOMER
  ],
  ADMIN_COLAB: [
    PERMISSIONS.CREATE_BRANCH,
    PERMISSIONS.CREATE_PERSONAL,
    PERMISSIONS.CREATE_CAR,
    PERMISSIONS.CREATE_CUSTOMER,   
     
    PERMISSIONS.CREATE_REGTRANSACTION,
    PERMISSIONS.CREATE_REGDEPOSIT,  
    PERMISSIONS.DEPOSITS,
    PERMISSIONS.MEMORANDUM,
    PERMISSIONS.PAGO_COMISION,  
    PERMISSIONS.PAGO_COMPRAS,
    PERMISSIONS.PAGO_SOLICITUDES,
    PERMISSIONS.RESTITUCIONES,
    PERMISSIONS.CIERRE_CAJA
  ],
  
  ASESOR_FINANCIERO: [
  
  ],
  ASESOR_VENTAS: [
  
  ],
}