import type { Role } from "./roles"

export const PERMISSIONS = {
  // Genérico

  //========= REGISTROS==========
  //Sucursales
  CREATE_BRANCH: "CREATE_BRANCH",
  // Personal
  CREATE_PERSONAL: "CREATE_PERSONAL",
  // Transacciones
  CREATE_REGDEPOSIT: "CREATE_REGDEPOSIT",
  CREATE_REGTRANSACTION: "CREATE_REGTRANSACTION",
  CREATE_DEBT: "CREATE_DEBT",
  CREATE_CAR: "CREATE_CAR",
  CREATE_CUSTOMER: "CREATE_CUSTOMER",

  // ======== INGRESOS ==========
  DEPOSITS: "DEPOSITS",
  COLLECT_DEBT: "COLLECT_DEBT",
  MEMORANDUM: "MEMORANDUM",

  // ======== EGRESOS  =========
  PAGO_COMISION: "PAGO_COMISION",
  PAGO_SUELDO: "PAGO_SUELDO",
  PAGO_SERVICIOS: "PAGO_SERVICIOS",
  PAGO_ALQUILER: "PAGO_ALQUILER",
  PAGO_COMPRAS: "PAGO_COMPRAS",
  DEVOLUCIONES: "DEVOLUVIONES"
 

} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  
  GERENTE: [
    PERMISSIONS.CREATE_BRANCH,
    PERMISSIONS.CREATE_PERSONAL,
    PERMISSIONS.CREATE_REGTRANSACTION,
    PERMISSIONS.CREATE_REGDEPOSIT,
    PERMISSIONS.COLLECT_DEBT,
    PERMISSIONS.CREATE_CAR,
    PERMISSIONS.CREATE_CUSTOMER,
    PERMISSIONS.DEPOSITS,
    PERMISSIONS.MEMORANDUM,
    PERMISSIONS.PAGO_COMISION,  
    PERMISSIONS.PAGO_SUELDO,
    PERMISSIONS.PAGO_SERVICIOS,
    PERMISSIONS.PAGO_ALQUILER,
    PERMISSIONS.PAGO_COMPRAS,
    PERMISSIONS.DEVOLUCIONES
  ],

  ADMIN: [
    PERMISSIONS.CREATE_PERSONAL,
    PERMISSIONS.CREATE_REGTRANSACTION,
    PERMISSIONS.CREATE_REGDEPOSIT,
    PERMISSIONS.CREATE_CAR,
    PERMISSIONS.CREATE_CUSTOMER,
    PERMISSIONS.DEPOSITS,
     PERMISSIONS.PAGO_COMPRAS,
    PERMISSIONS.MEMORANDUM
  ],

  JEFE_PERSONAL: [
    PERMISSIONS.CREATE_PERSONAL,
    PERMISSIONS.CREATE_REGTRANSACTION,
    PERMISSIONS.CREATE_REGDEPOSIT,
    PERMISSIONS.CREATE_CAR,
    PERMISSIONS.CREATE_CUSTOMER
  ],
  ASESOR_FINANCIERO: [
  
  ],
  ASESOR_VENTAS: [
  
  ],
}